// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://yf2l7ww5bjdq5j7q2uqoodxaqi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ny2z5wqdi5adxaw3pp4r4q3ky4",
    "aws_content_delivery_bucket": "pppteam1-20200225202020-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://pppteam1-20200225202020-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
